### ISSUE TITLE
More issues with 'package_pqclean.sh'

### ISSUE THREAD

**Issue by mouse07410** [jschanck/ntru#18]
The version of `cp` command on Mac does not take `-l` flag. My way of remedying this was installing `coreutils` package from Macports, and changing the script to use `gcp` instead of `cp`, like
```diff
   ( cd ${WORKDIR}/ref-${PARAM}/
-    cp -l api.h cmov.h owcpa.h params.h poly.h sample.h ${DIRNAME}/ntru${PARAM}/clean/
-    cp -l cmov.c kem.c owcpa.c pack3.c packq.c poly.c poly_lift.c poly_mod.c poly_r2_inv.c poly_rq_mul.c poly_s3_inv.c sample.c sample_iid.c ${DIRNAME}/ntru${PARAM}/clean/ )
+    gcp -l api.h cmov.h owcpa.h params.h poly.h sample.h ${DIRNAME}/ntru${PARAM}/clean/
+    gcp -l cmov.c kem.c owcpa.c pack3.c packq.c poly.c poly_lift.c poly_mod.c poly_r2_inv.c poly_rq_mul.c poly_s3_inv.c sample.c sample_iid.c ${DIRNAME}/ntru${PARAM}/clean/ )
 
   ( cd ${WORKDIR}/avx2-${PARAM}/
```
While I'm **not** suggesting that the script is changed - perhaps it would make sense to add a platform README, or mention these things in the main README?

On CentOS-8 there's no `unifdef` (and no `astyle`, but the last one can be installed via `sudo yum install astyle` easily enough):
```
. . . . .
NTRU_NAMESPACE=PQCLEAN_NTRUHPS4096821_AVX2_ python3 asmgen/poly_s3_inv.py 820 | sed 's/4294967295/-1/g' > poly_s3_inv.c
./package_pqclean.sh: line 199: unifdef: command not found
./package_pqclean.sh: line 200: unifdef: command not found
./package_pqclean.sh: line 201: unifdef: command not found
./package_pqclean.sh: line 202: unifdef: command not found
./package_pqclean.sh: line 203: unifdef: command not found
./package_pqclean.sh: line 234: astyle: command not found
```
Interestingly, macOS does come with `unifdef`.

Also, if the directory already exists - there's an error message:
```
$ ./package_pqclean.sh 
/Users/ur20980/src/ntru
Error; directory already exists; delete first.
```
IMHO, it would be far better if the error message would tell the user **what** directory it means:
```diff
diff --git a/package_pqclean.sh b/package_pqclean.sh
index 87064b7..31d210e 100755
--- a/package_pqclean.sh
+++ b/package_pqclean.sh
@@ -8,7 +8,7 @@ echo $WORKDIR
 DIRNAME=${WORKDIR}/crypto_kem
 
 if [ -e "$DIRNAME" ]; then
-  echo "Error; directory already exists; delete first."
+  echo "Error; directory \"${DIRNAME}\" already exists; delete first."
   exit -1
 fi
 

```

**Comment by mouse07410** [comment]
And a question: is `crypto_kem` directory that `package_pqclean.sh` creates, pretty much the complete KEM part of PQClean? I.e., if all I need is a KEM library, this directory would be sufficient? Or do I still need to pull PQClean repo?

**Comment by jschanck** [comment]
I changed the cp -l into cp -L. This script is for people who maintain the pqclean project. It's not meant to create anything useful for end users.
