### ISSUE TITLE
(question) how use just the PKE ?

### ISSUE THREAD

**Issue by danieagle** [jschanck/ntru#20]
Hi!
How to use PKE ? I need an example.

Really Thanks for the lib and care.

[]'s Dani.

**Comment by jschanck** [comment]
Do you mean the PKE or the KEM? You should not attempt to use the underlying PKE.

If you mean the KEM, use PQClean (https://github.com/PQClean/PQClean) and follow these instructions:
https://github.com/PQClean/PQClean#using-source-code-from-pqclean-in-your-own-project
