### ISSUE TITLE
(question) what is the maximum length of encapsulate key (plain text) ?

### ISSUE THREAD

**Issue by danieagle** [jschanck/ntru#21]
Hi!
  What is the maximum length of encapsulate key (plain text) ?

  Motive: I need use the kem with a aes ctr mode.  Beyond the key itself (256bits),
the decryption part need the IV(nonce) used to encryption to be sended with the key. the IV has
length of 128bits. I'm targeting ref-hps4096821.

Thanks!
Best whishes, 
Dani.

**Comment by jschanck** [comment]
Hi Dani, ntruhps4096821 outputs a 256 bit key. For counter mode it's perfectly fine to start your counter at 0.
