### ISSUE TITLE
Mismatched array sizes in poly.h / pack3.c

### ISSUE THREAD

**Issue by dstebila** [jschanck/ntru#24]
Compiling liboqs with gcc-11 complains about mismatched array sizes in the declaration of `poly_S3_tobytes` and `poly_S3_frombytes` in poly.h versus the instantiation in pack3.c:

The declaration in poly.h uses:
```c
void poly_S3_tobytes(unsigned char msg[NTRU_PACK_TRINARY_BYTES], const poly *a);
void poly_S3_frombytes(poly *r, const unsigned char msg[NTRU_PACK_TRINARY_BYTES]);
```
but the instantiation in pack3.c uses:
```c
void poly_S3_tobytes(unsigned char msg[NTRU_OWCPA_MSGBYTES], const poly *a) {...}
void poly_S3_frombytes(poly *r, const unsigned char msg[NTRU_OWCPA_MSGBYTES]) {...}
```

I think the solution is just to change pack3.c to use `NTRU_PACK_TRINARY_BYTES`. At least that seems to fix the compilation error.

See https://github.com/open-quantum-safe/liboqs/issues/1035 and https://github.com/PQClean/PQClean/issues/411.

**Comment by jschanck** [comment]
Thanks, Douglas! I'll package for PQClean and it will make its way down to liboqs from there.
